version: '3.8'
services:
  enqueue:
    build: .
    depends_on:
      - queue
    command: python enqueue.py
  queue:
    image: redis:6-alpine
    ports:
      - '6379:6379'
  worker1:
    build: .
    depends_on:
      - queue
    command: python worker.py
  worker2:
    build: .
    depends_on:
      - queue
    command: python worker.py
